kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: encrypted-gp3
parameters:
  fsType: ext4
  type: gp3
  encrypted: "true"
provisioner: ebs.csi.aws.com 
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer