
# ingress stuff
inboundcidrs: '0.0.0.0/0' #You probably want to limit this to your org's outbound IP addresses
certificatearn: 

sslpolicy:  ELBSecurityPolicy-TLS13-1-2-2021-06 #

namespace: password-manager

# Deployment stuff
# as discussed in the docs you will need to download the docker image then push it to your repo.
# at this time I am unaware of any public repo for pwm
image:
  repo: XXXXXXXXXXXX.dkr.ecr.us-west-1.amazonaws.com/pwm-project/pwm 
  tag: 2.0.8

resources:
  limits:
    memory: "2Gi"
    cpu: "2000m"
  requests:
    memory: "2Gi"
    cpu: "1000m"

# storage stuff
storage: 40Gi
storageclassname: encrypted-gp3
