apiVersion: v1
kind: ServiceAccount
metadata:
  name: pwm-admin
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pwm-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pwm-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pwm-admin
subjects:
- kind: ServiceAccount
  name: pwm-admin
  namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: Secret
metadata:
  name: pwm-token-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: pwm-admin
type: kubernetes.io/service-account-token