apiVersion: v1
kind: Service
metadata:
  name: pwm-service
  namespace: {{ .Values.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: pwm-server
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: pwm-web
      port: 8443
      targetPort: 8443
    # - name: pwm-http
    #   port: 8080
    #   targetPort: 8080

