

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pwm-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageclassname }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage }}
